// Generated by scripts/gen-types.py. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      bookings: {
        Row: {
          id: string
          session_id: string
          user_id: string
          status: Database["public"]["Enums"]["booking_status"]
          paid_with: Database["public"]["Enums"]["paid_with"]
          amount_pence: number
          class_pass_id: string | null
          membership_id: string | null
          order_id: string | null
          checked_in_at: string | null
          cancelled_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          user_id: string
          status?: Database["public"]["Enums"]["booking_status"]
          paid_with: Database["public"]["Enums"]["paid_with"]
          amount_pence?: number
          class_pass_id?: string | null
          membership_id?: string | null
          order_id?: string | null
          checked_in_at?: string | null
          cancelled_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          user_id?: string
          status?: Database["public"]["Enums"]["booking_status"]
          paid_with?: Database["public"]["Enums"]["paid_with"]
          amount_pence?: number
          class_pass_id?: string | null
          membership_id?: string | null
          order_id?: string | null
          checked_in_at?: string | null
          cancelled_at?: string | null
          created_at?: string
        }
        Relationships: [
          { foreignKeyName: "bookings_session_id_fkey"; columns: ["session_id"]; isOneToOne: false; referencedRelation: "class_sessions"; referencedColumns: ["id"] },
          { foreignKeyName: "bookings_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "bookings_class_pass_id_fkey"; columns: ["class_pass_id"]; isOneToOne: false; referencedRelation: "class_passes"; referencedColumns: ["id"] },
          { foreignKeyName: "bookings_membership_id_fkey"; columns: ["membership_id"]; isOneToOne: false; referencedRelation: "memberships"; referencedColumns: ["id"] },
          { foreignKeyName: "bookings_order_fk"; columns: ["order_id"]; isOneToOne: false; referencedRelation: "orders"; referencedColumns: ["id"] },
        ]
      }
      broadcasts: {
        Row: {
          id: string
          created_by: string | null
          channel: string
          audience: Json
          subject: string | null
          body: string
          recipient_count: number
          sent_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          created_by?: string | null
          channel: string
          audience: Json
          subject?: string | null
          body: string
          recipient_count?: number
          sent_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          created_by?: string | null
          channel?: string
          audience?: Json
          subject?: string | null
          body?: string
          recipient_count?: number
          sent_at?: string | null
          created_at?: string
        }
        Relationships: [
          { foreignKeyName: "broadcasts_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      class_pass_products: {
        Row: {
          id: string
          name: string
          description: string | null
          credits: number
          price_pence: number
          validity_days: number
          stripe_price_id: string | null
          sort_order: number
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          credits: number
          price_pence: number
          validity_days?: number
          stripe_price_id?: string | null
          sort_order?: number
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          credits?: number
          price_pence?: number
          validity_days?: number
          stripe_price_id?: string | null
          sort_order?: number
          active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      class_passes: {
        Row: {
          id: string
          user_id: string
          product_id: string | null
          credits_total: number
          credits_remaining: number
          expires_at: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          product_id?: string | null
          credits_total: number
          credits_remaining: number
          expires_at: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          product_id?: string | null
          credits_total?: number
          credits_remaining?: number
          expires_at?: string
          created_at?: string
        }
        Relationships: [
          { foreignKeyName: "class_passes_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "class_passes_product_id_fkey"; columns: ["product_id"]; isOneToOne: false; referencedRelation: "class_pass_products"; referencedColumns: ["id"] },
        ]
      }
      class_sessions: {
        Row: {
          id: string
          class_type_id: string
          teacher_id: string | null
          location_id: string | null
          starts_at: string
          ends_at: string
          capacity: number
          pricing: Database["public"]["Enums"]["pricing_mode"]
          drop_in_pence: number
          suggested_pwyw_pence: number | null
          status: Database["public"]["Enums"]["session_status"]
          cancel_reason: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          class_type_id: string
          teacher_id?: string | null
          location_id?: string | null
          starts_at: string
          ends_at: string
          capacity?: number
          pricing?: Database["public"]["Enums"]["pricing_mode"]
          drop_in_pence?: number
          suggested_pwyw_pence?: number | null
          status?: Database["public"]["Enums"]["session_status"]
          cancel_reason?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          class_type_id?: string
          teacher_id?: string | null
          location_id?: string | null
          starts_at?: string
          ends_at?: string
          capacity?: number
          pricing?: Database["public"]["Enums"]["pricing_mode"]
          drop_in_pence?: number
          suggested_pwyw_pence?: number | null
          status?: Database["public"]["Enums"]["session_status"]
          cancel_reason?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          { foreignKeyName: "class_sessions_class_type_id_fkey"; columns: ["class_type_id"]; isOneToOne: false; referencedRelation: "class_types"; referencedColumns: ["id"] },
          { foreignKeyName: "class_sessions_teacher_id_fkey"; columns: ["teacher_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "class_sessions_location_id_fkey"; columns: ["location_id"]; isOneToOne: false; referencedRelation: "locations"; referencedColumns: ["id"] },
        ]
      }
      class_types: {
        Row: {
          id: string
          name: string
          description: string | null
          duration_minutes: number
          colour: string
          default_capacity: number
          default_pricing: Database["public"]["Enums"]["pricing_mode"]
          default_drop_in_pence: number
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          duration_minutes?: number
          colour?: string
          default_capacity?: number
          default_pricing?: Database["public"]["Enums"]["pricing_mode"]
          default_drop_in_pence?: number
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          duration_minutes?: number
          colour?: string
          default_capacity?: number
          default_pricing?: Database["public"]["Enums"]["pricing_mode"]
          default_drop_in_pence?: number
          active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      event_tickets: {
        Row: {
          id: string
          event_id: string
          name: string
          price_pence: number
          member_price_pence: number | null
          members_only: boolean
          quantity: number | null
          sort_order: number
        }
        Insert: {
          id?: string
          event_id: string
          name: string
          price_pence: number
          member_price_pence?: number | null
          members_only?: boolean
          quantity?: number | null
          sort_order?: number
        }
        Update: {
          id?: string
          event_id?: string
          name?: string
          price_pence?: number
          member_price_pence?: number | null
          members_only?: boolean
          quantity?: number | null
          sort_order?: number
        }
        Relationships: [
          { foreignKeyName: "event_tickets_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
        ]
      }
      events: {
        Row: {
          id: string
          title: string
          slug: string
          description: string | null
          image_url: string | null
          location_id: string | null
          starts_at: string
          ends_at: string | null
          capacity: number | null
          status: Database["public"]["Enums"]["event_status"]
          created_at: string
        }
        Insert: {
          id?: string
          title: string
          slug: string
          description?: string | null
          image_url?: string | null
          location_id?: string | null
          starts_at: string
          ends_at?: string | null
          capacity?: number | null
          status?: Database["public"]["Enums"]["event_status"]
          created_at?: string
        }
        Update: {
          id?: string
          title?: string
          slug?: string
          description?: string | null
          image_url?: string | null
          location_id?: string | null
          starts_at?: string
          ends_at?: string | null
          capacity?: number | null
          status?: Database["public"]["Enums"]["event_status"]
          created_at?: string
        }
        Relationships: [
          { foreignKeyName: "events_location_id_fkey"; columns: ["location_id"]; isOneToOne: false; referencedRelation: "locations"; referencedColumns: ["id"] },
        ]
      }
      locations: {
        Row: {
          id: string
          name: string
          address: string | null
          notes: string | null
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          address?: string | null
          notes?: string | null
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          address?: string | null
          notes?: string | null
          active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      membership_plans: {
        Row: {
          id: string
          name: string
          description: string | null
          price_pence: number
          interval: string
          classes_per_period: number | null
          stripe_price_id: string | null
          event_discount_percent: number
          sort_order: number
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          price_pence: number
          interval?: string
          classes_per_period?: number | null
          stripe_price_id?: string | null
          event_discount_percent?: number
          sort_order?: number
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          price_pence?: number
          interval?: string
          classes_per_period?: number | null
          stripe_price_id?: string | null
          event_discount_percent?: number
          sort_order?: number
          active?: boolean
          created_at?: string
        }
        Relationships: []
      }
      memberships: {
        Row: {
          id: string
          user_id: string
          plan_id: string
          status: Database["public"]["Enums"]["membership_status"]
          stripe_subscription_id: string | null
          current_period_start: string | null
          current_period_end: string | null
          paused_until: string | null
          cancel_at: string | null
          started_at: string
          ended_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          plan_id: string
          status?: Database["public"]["Enums"]["membership_status"]
          stripe_subscription_id?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          paused_until?: string | null
          cancel_at?: string | null
          started_at?: string
          ended_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          plan_id?: string
          status?: Database["public"]["Enums"]["membership_status"]
          stripe_subscription_id?: string | null
          current_period_start?: string | null
          current_period_end?: string | null
          paused_until?: string | null
          cancel_at?: string | null
          started_at?: string
          ended_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          { foreignKeyName: "memberships_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "memberships_plan_id_fkey"; columns: ["plan_id"]; isOneToOne: false; referencedRelation: "membership_plans"; referencedColumns: ["id"] },
        ]
      }
      orders: {
        Row: {
          id: string
          user_id: string | null
          kind: Database["public"]["Enums"]["order_kind"]
          status: Database["public"]["Enums"]["order_status"]
          amount_pence: number
          currency: string
          description: string | null
          membership_id: string | null
          class_pass_id: string | null
          session_id: string | null
          event_id: string | null
          event_ticket_id: string | null
          quantity: number
          stripe_checkout_session_id: string | null
          stripe_payment_intent_id: string | null
          stripe_invoice_id: string | null
          metadata: Json
          created_at: string
          paid_at: string | null
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          kind: Database["public"]["Enums"]["order_kind"]
          status?: Database["public"]["Enums"]["order_status"]
          amount_pence?: number
          currency?: string
          description?: string | null
          membership_id?: string | null
          class_pass_id?: string | null
          session_id?: string | null
          event_id?: string | null
          event_ticket_id?: string | null
          quantity?: number
          stripe_checkout_session_id?: string | null
          stripe_payment_intent_id?: string | null
          stripe_invoice_id?: string | null
          metadata?: Json
          created_at?: string
          paid_at?: string | null
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          kind?: Database["public"]["Enums"]["order_kind"]
          status?: Database["public"]["Enums"]["order_status"]
          amount_pence?: number
          currency?: string
          description?: string | null
          membership_id?: string | null
          class_pass_id?: string | null
          session_id?: string | null
          event_id?: string | null
          event_ticket_id?: string | null
          quantity?: number
          stripe_checkout_session_id?: string | null
          stripe_payment_intent_id?: string | null
          stripe_invoice_id?: string | null
          metadata?: Json
          created_at?: string
          paid_at?: string | null
          updated_at?: string
        }
        Relationships: [
          { foreignKeyName: "orders_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "orders_membership_id_fkey"; columns: ["membership_id"]; isOneToOne: false; referencedRelation: "memberships"; referencedColumns: ["id"] },
          { foreignKeyName: "orders_class_pass_id_fkey"; columns: ["class_pass_id"]; isOneToOne: false; referencedRelation: "class_passes"; referencedColumns: ["id"] },
          { foreignKeyName: "orders_session_id_fkey"; columns: ["session_id"]; isOneToOne: false; referencedRelation: "class_sessions"; referencedColumns: ["id"] },
          { foreignKeyName: "orders_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
          { foreignKeyName: "orders_event_ticket_id_fkey"; columns: ["event_ticket_id"]; isOneToOne: false; referencedRelation: "event_tickets"; referencedColumns: ["id"] },
        ]
      }
      outbox_events: {
        Row: {
          id: string
          type: string
          user_id: string | null
          payload: Json
          created_at: string
          delivered_at: string | null
          attempts: number
          last_error: string | null
        }
        Insert: {
          id?: string
          type: string
          user_id?: string | null
          payload?: Json
          created_at?: string
          delivered_at?: string | null
          attempts?: number
          last_error?: string | null
        }
        Update: {
          id?: string
          type?: string
          user_id?: string | null
          payload?: Json
          created_at?: string
          delivered_at?: string | null
          attempts?: number
          last_error?: string | null
        }
        Relationships: [
          { foreignKeyName: "outbox_events_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ]
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          phone: string | null
          whatsapp_opt_in: boolean
          marketing_opt_in: boolean
          role: Database["public"]["Enums"]["user_role"]
          stripe_customer_id: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          phone?: string | null
          whatsapp_opt_in?: boolean
          marketing_opt_in?: boolean
          role?: Database["public"]["Enums"]["user_role"]
          stripe_customer_id?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          phone?: string | null
          whatsapp_opt_in?: boolean
          marketing_opt_in?: boolean
          role?: Database["public"]["Enums"]["user_role"]
          stripe_customer_id?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      settings: {
        Row: {
          id: number
          club_name: string
          whatsapp_community_url: string | null
          whatsapp_team_numbers: string[]
          booking_cutoff_minutes: number
          cancel_cutoff_hours: number
          orange_after_days: number
          red_after_days: number
          timezone: string
          updated_at: string
        }
        Insert: {
          id?: number
          club_name?: string
          whatsapp_community_url?: string | null
          whatsapp_team_numbers?: string[]
          booking_cutoff_minutes?: number
          cancel_cutoff_hours?: number
          orange_after_days?: number
          red_after_days?: number
          timezone?: string
          updated_at?: string
        }
        Update: {
          id?: number
          club_name?: string
          whatsapp_community_url?: string | null
          whatsapp_team_numbers?: string[]
          booking_cutoff_minutes?: number
          cancel_cutoff_hours?: number
          orange_after_days?: number
          red_after_days?: number
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      engagement: {
        Row: {
          user_id: string | null
          full_name: string | null
          email: string | null
          phone: string | null
          whatsapp_opt_in: boolean | null
          is_member: boolean | null
          membership_status: Database["public"]["Enums"]["membership_status"] | null
          member_since: string | null
          last_attended_at: string | null
          classes_30d: number | null
          upcoming: number | null
          flag: Database["public"]["Enums"]["engagement_flag"] | null
        }
        Relationships: []
      }
      session_booking_counts: {
        Row: {
          session_id: string | null
          booked: number | null
          waitlisted: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      current_role_of: { Args: { uid: string }; Returns: Database["public"]["Enums"]["user_role"] }
      is_staff: { Args: {  }; Returns: boolean }
      is_admin: { Args: {  }; Returns: boolean }
      is_active_member: { Args: { uid: string }; Returns: boolean }
      emit_event: { Args: { p_type: string; p_user_id: string; p_payload: Json }; Returns: string }
    }
    Enums: {
      booking_status: "booked" | "waitlisted" | "cancelled" | "attended" | "no_show"
      engagement_flag: "green" | "orange" | "red" | "new" | "inactive"
      event_status: "draft" | "published" | "cancelled" | "completed"
      membership_status: "active" | "paused" | "past_due" | "cancelled" | "incomplete"
      order_kind: "membership" | "class_pass" | "drop_in" | "pay_what_you_wish" | "event_ticket" | "donation"
      order_status: "pending" | "paid" | "refunded" | "failed" | "cancelled"
      paid_with: "membership" | "class_pass" | "drop_in" | "pay_what_you_wish" | "free" | "comp"
      pricing_mode: "members_included" | "drop_in" | "pay_what_you_wish" | "free"
      session_status: "scheduled" | "cancelled" | "completed"
      user_role: "yogi" | "teacher" | "admin"
    }
    CompositeTypes: Record<string, never>
  }
}

export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"]
export type Views<T extends keyof Database["public"]["Views"]> = Database["public"]["Views"][T]["Row"]
export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T]
