#!/usr/bin/env python3
"""
Generate src/lib/database.types.ts (supabase-js Database shape) from a live Postgres.
Usage: python3 scripts/gen-types.py "postgresql://postgres@127.0.0.1:5433/stars_test"
Needs only psql on PATH. Used because `supabase gen types` requires Docker.
"""
import json, subprocess, sys

db = sys.argv[1] if len(sys.argv) > 1 else "postgresql://postgres@127.0.0.1:5433/stars_test"

def q(sql):
    out = subprocess.run(["psql", db, "-t", "-A", "-c", sql], capture_output=True, text=True, check=True).stdout
    return [line for line in out.splitlines() if line]

PG_TO_TS = {
    "uuid": "string", "text": "string", "varchar": "string", "character varying": "string", "citext": "string",
    "integer": "number", "int4": "number", "bigint": "number", "int8": "number", "smallint": "number", "numeric": "number", "real": "number", "double precision": "number",
    "boolean": "boolean", "bool": "boolean",
    "timestamp with time zone": "string", "timestamptz": "string", "timestamp without time zone": "string", "date": "string", "time": "string",
    "jsonb": "Json", "json": "Json",
}

enums = {}
for row in q("select t.typname, string_agg(e.enumlabel, '|' order by e.enumsortorder) from pg_type t join pg_enum e on e.enumtypid=t.oid join pg_namespace n on n.oid=t.typnamespace where n.nspname='public' group by t.typname"):
    name, labels = row.split("|", 1)
    enums[name] = labels.split("|")

def ts_type(data_type, udt, is_array=False):
    if udt in enums:
        t = f'Database["public"]["Enums"]["{udt}"]'
    elif data_type == "ARRAY":
        return ts_type(None, udt.lstrip("_")) + "[]"
    else:
        t = PG_TO_TS.get(data_type) or PG_TO_TS.get(udt) or "unknown"
    return t

def columns(kind):
    sql = f"""
    select c.table_name, c.column_name, c.data_type, c.udt_name, c.is_nullable, c.column_default is not null or c.is_identity='YES', c.ordinal_position
    from information_schema.columns c
    join information_schema.tables t on t.table_name=c.table_name and t.table_schema=c.table_schema
    where c.table_schema='public' and t.table_type='{kind}'
    order by c.table_name, c.ordinal_position"""
    rows = {}
    for line in q(sql):
        table, col, dtype, udt, nullable, has_default, _ = line.split("|")
        rows.setdefault(table, []).append((col, ts_type(dtype, udt), nullable == "YES", has_default == "t"))
    return rows

tables = columns("BASE TABLE")
views = columns("VIEW")

fks = {}
for line in q("""
select tc.table_name, kcu.column_name, ccu.table_name, ccu.column_name, tc.constraint_name
from information_schema.table_constraints tc
join information_schema.key_column_usage kcu on kcu.constraint_name=tc.constraint_name and kcu.table_schema=tc.table_schema
join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema
where tc.constraint_type='FOREIGN KEY' and tc.table_schema='public'"""):
    t, c, rt, rc, name = line.split("|")
    fks.setdefault(t, []).append((name, c, rt, rc))

functions = {}
for line in q("""
select p.proname, pg_get_function_arguments(p.oid), pg_get_function_result(p.oid)
from pg_proc p join pg_namespace n on n.oid=p.pronamespace
where n.nspname='public' and p.prokind='f' and p.proname not like 'handle_%' and p.proname <> 'set_updated_at' and not exists (select 1 from pg_depend d where d.objid=p.oid and d.deptype='e')"""):
    name, args, ret = line.split("|")
    functions[name] = (args, ret)

def emit_cols(cols, mode):
    out = []
    for col, t, nullable, has_default in cols:
        typ = f"{t} | null" if nullable else t
        if mode == "Row":
            out.append(f"          {col}: {typ}")
        elif mode == "Insert":
            opt = "?" if (nullable or has_default) else ""
            out.append(f"          {col}{opt}: {typ}")
        else:
            out.append(f"          {col}?: {typ}")
    return "\n".join(out)

lines = []
lines.append("// Generated by scripts/gen-types.py. Do not edit by hand.")
lines.append("export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]\n")
lines.append("export type Database = {")
lines.append("  public: {")
lines.append("    Tables: {")
for t, cols in tables.items():
    lines.append(f"      {t}: {{")
    lines.append("        Row: {\n" + emit_cols(cols, "Row") + "\n        }")
    lines.append("        Insert: {\n" + emit_cols(cols, "Insert") + "\n        }")
    lines.append("        Update: {\n" + emit_cols(cols, "Update") + "\n        }")
    rels = fks.get(t, [])
    if rels:
        lines.append("        Relationships: [")
        for name, c, rt, rc in rels:
            lines.append(f'          {{ foreignKeyName: "{name}"; columns: ["{c}"]; isOneToOne: false; referencedRelation: "{rt}"; referencedColumns: ["{rc}"] }},')
        lines.append("        ]")
    else:
        lines.append("        Relationships: []")
    lines.append("      }")
lines.append("    }")
lines.append("    Views: {")
for v, cols in views.items():
    lines.append(f"      {v}: {{")
    lines.append("        Row: {\n" + emit_cols([(c, t, True, False) for c, t, _, _ in cols], "Row") + "\n        }")
    lines.append("        Relationships: []")
    lines.append("      }")
lines.append("    }")
lines.append("    Functions: {")
for f, (args, ret) in functions.items():
    def arg_ts(a):
        a = a.strip()
        if not a:
            return None
        if " " not in a:
            return None
        n, ty = a.split(" ", 1)
        return f"{n}: {ts_type(ty, ty)}"
    argl = [x for x in (arg_ts(a) for a in args.split(",")) if x]
    ret_ts = ts_type(ret, ret)
    lines.append(f"      {f}: {{ Args: {{ {'; '.join(argl)} }}; Returns: {ret_ts} }}")
lines.append("    }")
lines.append("    Enums: {")
for e, labels in enums.items():
    lines.append(f"      {e}: " + " | ".join(json.dumps(l) for l in labels))
lines.append("    }")
lines.append("    CompositeTypes: Record<string, never>")
lines.append("  }")
lines.append("}\n")
lines.append('export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"]')
lines.append('export type Views<T extends keyof Database["public"]["Views"]> = Database["public"]["Views"][T]["Row"]')
lines.append('export type Enums<T extends keyof Database["public"]["Enums"]> = Database["public"]["Enums"][T]')

open("src/lib/database.types.ts", "w").write("\n".join(lines) + "\n")
print(f"wrote src/lib/database.types.ts: {len(tables)} tables, {len(views)} views, {len(enums)} enums, {len(functions)} functions")
